name: Laravel Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: laravel
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - uses: actions/checkout@v2

    - name: Copy .env
      run: cp .env.example .env

    - name: Install Dependencies
      run: |
        composer install --prefer-dist --no-progress --no-suggest

    - name: Generate Key
      run: php artisan key:generate

    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache

    - name: Create Database
      run: mysql -e 'CREATE DATABASE IF NOT EXISTS laravel;' -uroot -ppassword -h127.0.0.1

    - name: Migrate
      run: php artisan migrate

    - name: Run Queue
      run: php artisan queue:work --daemon

    - name: Database Seeding
      run: php artisan db:seed

    - name: Run Tests
      run: php artisan test